version: "3.8"

services:
  db:
    image: postgres:15-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=bank
    shm_size: 1g
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "bank" ]
      interval: 2s
      timeout: 2s
      retries: 10
    networks:
      - db

  dev:
    build:
      context: .
      target: production
    command: python -m app
    depends_on:
      db:
        condition: service_healthy
    env_file: test.env
    networks:
      - db

  test:
    &test
    build:
      context: .
      target: development
    env_file: test.env

  test_integration:
    <<: *test
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db

  bash:
    tty: true
    build:
      context: .
      target: development
    volumes:
      - type: bind
        source: ./
        target: /app/.

networks:
  db:
    name: db
